<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>namter-data-publisher</AssemblyName>
    <NamterRepositoryRoot>$([System.IO.Path]::GetFullPath('$(MSBuildProjectDirectory)\..\..\..'))</NamterRepositoryRoot>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Reflection.AssemblyMetadataAttribute">
      <_Parameter1>NamterRepositoryRoot</_Parameter1>
      <_Parameter2>$(NamterRepositoryRoot)</_Parameter2>
    </AssemblyAttribute>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
    <ProjectReference Include="..\Namter.GameData\Namter.GameData.csproj" />
  </ItemGroup>
</Project>
